apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - port: 3010
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
### kubectl expose pod nginx-pod --type=NodePort -port=80
